### ISSUE TITLE
Check unnecessary copies of data structures

### ISSUE THREAD

**Issue by pmelchior** [pmelchior/scarlet#101]
We have many places where we copy sed, psfs, morphologies etc. Given the high memory demand of the code and the performance target, let's make sure we don't waste time on unnecessary copies.

**Comment by fred3m** [comment]
Never mind my comment in the PR, you are right. If we want my intended functionality we need to pass `copy=False` to the array wrappers.

**Comment by pmelchior** [comment]
#147 addresses this issue in multiple ways:
* sources are in boxes
* parameters are generated by source models without any copying
