### ISSUE TITLE
Handle point sources correctly

### ISSUE THREAD

**Issue by fred3m** [pmelchior/scarlet#108]
Currently the code allows users to initialize a source as a `PointSource` and allow the user to either fix its morphology or update as if it was an extended source. This does not account for updates to the source position, which will likely be required to shift the source to a fractional pixel position. So we should come up with a simple way of flagging a point source to allow it to update the morphology based on a position shift but not a gradient update.

In this ticket we should also fix the way that we skip sources with a fixed sed and/or morphology. Currently `autograd` calculates gradients for all sources, even morphologies when `fix_morph=True`. This not only wastes CPU time but will also generate suboptimal updates to the gradients of the other sources.

**Comment by pmelchior** [comment]
Closed with development in the `adam` branch
