### ISSUE TITLE
Choose fast sizes for FFT in Blend frame

### ISSUE THREAD

**Issue by pmelchior** [pmelchior/scarlet#111]
The speed of FFTs is strongly dependent on the size of the arrays. The reference frame should be chosen to have a number of pixels as a power of 2.

The minimal solution would be to log a warning if a `Frame` instance does not have a proper size. However, data frames don't need that because they'll never be FFTed. One could add an attribute to `Frame` to specify that it's for a model instead of data, but that's clunky. One could instead issue the warning if a `Component` is created with an improper frame, but then it's too late and the warning would be raised every time for k components. Raising it in `Blend` is still too late.

I still think the first option is best: raising a warning whenever a Frame is created. It would also prevent someone from using a data frame for the model.

**Comment by fred3m** [comment]
It's not quite that simple. See https://docs.scipy.org/doc/scipy/reference/generated/scipy.fftpack.next_fast_len.html . In short you are looking for the nearest factor of 2, 3, or 5, since those are the primes that fftpack (which is what numpy uses) are optimized for. This can be 100's of times faster, as they describe in the link.

**Comment by pmelchior** [comment]
This is quite a rabbit hole. It's easy to issue a warning that the size isn't well-chosen, but if the user acts on it and changes the size of the blend frame, we have a size mismatch.
The init functions for several sources and the loss of `Observation` all assume that the data and the mode frame have the same size. This relation would be broken.

Given problems with padding and objects at the edges, we will probably have to consider slices to match the spatial footprints of model and data frame. In `LowResObservation` we already have one of those slices (in data space), but all observations need both slices (in model space if the model encompasses the data; and in data space if the data encompasses the model). This would allow us to grow the model explicitly to reduce problems at the edges. 

This issue does not deal with how to pick the frame sizes given a set of sources and observations, but it should enable us to be flexible about it.

**Comment by pmelchior** [comment]
In #124 we thought that we don't need the resizing of the Blend frame because the model is padded to a fast size anyway before it is convolved. But the symmetry update still operates on the model frame as is, which makes this operation still inefficient. We might be able to close this issue with improvements from #110

**Comment by pmelchior** [comment]
Since we're not using k-space symmetry and we use fast sizes in `FFT`, this issue is largely mute.
