### ISSUE TITLE
Symmetry is broken for even numbered rows or columns

### ISSUE THREAD

**Issue by fred3m** [pmelchior/scarlet#117]
When running symmetry with an even number of rows or columns the algorithm is broken, in that sources are shifted from their correct spot, creating strange features.

![blend_60_symmetric](https://user-images.githubusercontent.com/2251900/60759639-a6293380-9ff6-11e9-9132-624fab8ea715.png)

This doesn't happen if symmetry is turned off, and if I just remove the last column and row to make the image shape odd we get the correct behavior:

![blend_60_symmetric](https://user-images.githubusercontent.com/2251900/60759654-d2dd4b00-9ff6-11e9-97de-f560e1fe1321.png)

**Comment by fred3m** [comment]
Note: the above only happens when the sources are initialized as `PointSource` objects, not `ExtendedSource` objects. So this likely has something to do with the way the objects are initialized, and that point sources seem to have more difficulty finding their correct center with symmetry on.

**Comment by fred3m** [comment]
There's a good chance that this might be due to the centering algorithm. I've also found cases that work better with even rows/columns, so the deciding factor might be whether the source center is closer to the pixel center or halfway between two pixels.

**Comment by pmelchior** [comment]
Closed by developments in the `adam` branch
