### ISSUE TITLE
Update tutorials to work with interactive plots

### ISSUE THREAD

**Issue by fred3m** [pmelchior/scarlet#137]
Robert made a good point that some users may be using interactive plots in jupyter, which don't display properly using the current tutorials. Namely, the `%matplotlib inline` backend automatically closes figures on `plt.show()` and begins a new figure with the next plotting commend. This feature is convenient when using non-interactive plots, however interactive plots will overwrite the last axis that activated (`plt.gca()`). If we add a line to create a new figure explicitly before each plot our tutorials will be more robust.

**Comment by pmelchior** [comment]
I believe we fixed this recently. If so, please close.

**Comment by fred3m** [comment]
Fixed in https://github.com/pmelchior/scarlet/pull/161/commits/8c45d74c3923615dfe0b41711d23b16ee1258159
