### ISSUE TITLE
Weights in all data example files

### ISSUE THREAD

**Issue by pmelchior** [pmelchior/scarlet#143]
Since we will practically require users to set the observation weights, let's make sure that all data files we use for examples have them included. I haven't checked which ones do, but I suspect none.

To be specific: `weights` mean pixel inverse variance of the background limit (no Poissonian contribution, I think), with masked pixels set to 0.

**Comment by pmelchior** [comment]
I should mention that this will be relevant after #129 is closed. And we need to make sure that both tests and docs will follow the new change of constructing observations with weights as default.

**Comment by pmelchior** [comment]
This is only relevant for the point-source tutorial, where I set the weights by hand. @fred3m can you check the script where you generated the sources what the noise setting was?

**Comment by fred3m** [comment]
The noise for the simulations is generated using the `PoissonNoise` class in galsim:
https://github.com/lsst/testdata_deblender/blob/master/sim_data/settings.yaml#L20-L26
