### ISSUE TITLE
PSF subclass of Fourier

### ISSUE THREAD

**Issue by pmelchior** [pmelchior/scarlet#148]
When you talked about psf objects, I tought we were going to make them inherit from Fourier such that there is no need to create a new object for psfs when we want to make Fourier operations on them. I can take care of that in a following PR the case may be.

_Originally posted by @herjy in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MzI3NzI4NTg3/pull_request_reviews/more_threads_

**Comment by pmelchior** [comment]
@herjy is this issue still relevant?

**Comment by herjy** [comment]
I don't think it's actually usefull anymore. I'm happy to close it.

**Comment by pmelchior** [comment]
Please proceed
