### ISSUE TITLE
Consolidate the Observation class and avoid the multiplication of "types" of observations

### ISSUE THREAD

**Issue by herjy** [pmelchior/scarlet#176]
There are currently several different types of `Observation` classes that have different `match` and `render` methods. What class to use is either left to the user or handled by a method of `Frame` during the initialisation. 
In order to avoid the multiplication of such classes in future and the writing of long disparate `match` methods (thinking of prism observations), we propose to consolidate `Observation`s in a single class that will make decisions on which functions to call when executing `match` or `render` depending on which frame it is matched to.

We will internalise the process of decision-making as to the nature of what the methods of `Observation` do and we will externalise the current content of these methods by calling them from a different module. 
This will make it easier to understand `Observation` and ultimately to deal with new kinds of observations by avoiding having to write entire `Observation`-like classes that only differ by their `match` and `render functions`.

**Comment by pmelchior** [comment]
This is covered by #220 and #228
