### ISSUE TITLE
Programmatic versioning

### ISSUE THREAD

**Issue by kadrlica** [pmelchior/scarlet#185]
It would be nice to have internal versioning so that `scarlet.__version__` does what you would expect it to do. It would be double nice to have that versioning track the GitHub tagged version (or commit).

I've been pretty happy with [versioneer](https://github.com/warner/python-versioneer) for solving these issues. I could probably be convinced to help getting it setup if the developers would be interested.

**Comment by pmelchior** [comment]
Thanks, Alex. I didn't know versioneer before, and was thinking more along these lines [here](https://packaging.python.org/guides/single-sourcing-package-version/), especially a combination of ideas 1 and 6.

**Comment by kadrlica** [comment]
I think this is essentially what versioneer does, but it also syncs with the git tag and commits since the most recent tag.

**Comment by pmelchior** [comment]
We already have code for working with git tags, so I think we just have to connect a few dots.

Btw, have we really coded up the [same thing](https://github.com/pmelchior/skymapper) twice?

**Comment by kadrlica** [comment]
`skymap` and `skymapper` I don't think so, but you can ask some users who have used both (I know we talked about this a long time ago and decided to go our separate ways). `skymap` itself is coming close to EOL because of the deprecation of `basemap`, it's going to be replaced by [cartosky](https://github.com/kadrlica/cartosky).

**Comment by kadrlica** [comment]
With respect to connecting dots, it is completely up to you and the dev team. In my experience, there end up being quite a few edge cases and dots to connect.

**Comment by pmelchior** [comment]
Fixed by #197
