### ISSUE TITLE
Multi-resolution bug with point sources

### ISSUE THREAD

**Issue by herjy** [pmelchior/scarlet#194]
When initialising point sources in multi-resolution, the sources are created just fine, but running the get_model causes an error:
```
~/Desktop/LSST_Project/scarlet/scarlet/source.py in _psf_wrapper(self, *parameters)
    120 
    121     def _psf_wrapper(self, *parameters):
--> 122         return self.model_frame.psf.__call__(*parameters, bbox=self.bbox)[0]
```

**Comment by herjy** [comment]
The same thing happens in the new `factorized` branch.

**Comment by pmelchior** [comment]
This should be fixed by #204, specifically 0a798c7cedbcd51294acd53e6931d67e86269de1. Please confirm when the PR is merged

**Comment by herjy** [comment]
I think so too from what I read.

**Comment by pmelchior** [comment]
Can you confirm that this is fixed now?

**Comment by herjy** [comment]
Appologies, yes, I tested this and Iconfirm, this is fixed now. Closing the issue.
