### ISSUE TITLE
Starlet example notebook

### ISSUE THREAD

**Issue by pmelchior** [pmelchior/scarlet#195]
The current notebook I don't find that impressive. So, I agree with you that it should have its own notebook with a dedicated example, but we should attempt to keep the complications around detection to a minimum in that example notebook. So, I will keep the notebook, but we should find a better example.

_Originally posted by @pmelchior in https://github.com/pmelchior/scarlet/pull/191/review_comment/create_

**Comment by herjy** [comment]
I think I have one. I'll push it after this PR is done.
