### ISSUE TITLE
Bright sources artefacts from diff kernel error

### ISSUE THREAD

**Issue by herjy** [pmelchior/scarlet#215]
Tests on galsim simulations revealed ring-shaped artefacts in the residuals for bright sources. 
The rings are not caused by monotonicity or any of the constraints, neither are they remnants from initialisation. 
The suspected cause is an error introduced by the diff_kernel. The diff kernel indeed introduces very small errors to the PSF modeling ~10^-8%, which is small compared to the amplitude of the observed residuals:
<img width="988" alt="Screen Shot 2020-10-21 at 6 09 31 PM" src="https://user-images.githubusercontent.com/16084926/96793891-339abd80-13cb-11eb-97a5-68fb25022a06.png">

**Comment by herjy** [comment]
For reference, when comparing the data's psf and the psf constructed by convolving the model psf by the diff kernel, errors in log scale look like this: 
<img width="699" alt="Screen Shot 2020-10-21 at 6 33 51 PM" src="https://user-images.githubusercontent.com/16084926/96794351-07cc0780-13cc-11eb-87f1-27f58b28398c.png">

**Comment by herjy** [comment]
Double precision or rescaling of the central region did not solve the problem. I am convinced the problem comes from a wrapping or a small contraction/dilation of the Fourier plane.

**Comment by pmelchior** [comment]
Where would these dilations come from?

**Comment by herjy** [comment]
fft transform shapes/gridding. I haven't found anything yet playing with the fft code, so that might be wrong.

**Comment by pmelchior** [comment]
In the example above, the source is clearly truncated at the box. This can easily cause ringing as observed and would be independent of the correctness of the PSF diff kernel. Can you manually increase the box size to see if this has any effect?

There's one more test I like to make when everything becomes unclear. Initialize the source by hand with the correct deconvolved image as morphology. That means the solution is already at the maximum likelihood points. Check if the fitter computes non-zero gradients, i.e. it wants to walk away from it. If so, at least the backward path is biased.

**Comment by herjy** [comment]
That's not it, I checked before.
<img width="1000" alt="Screen Shot 2020-10-22 at 6 51 18 PM" src="https://user-images.githubusercontent.com/16084926/96938130-9ce80280-1497-11eb-9672-5166717cc373.png">
The residuals in the model look a lot like a sinc, but the difference between the psfs looks like a gaussian (all positive).

**Comment by pmelchior** [comment]
Is the original galaxy image from Galsim band-limited before it gets convolved?

**Comment by herjy** [comment]
Yes, because I convolve it with a small gaussian kernel to make sure it is.

**Comment by herjy** [comment]
I expanded this kernel from 1 pixel (which I thought was enough) to 1.5 pixels and it seems to do the trick.

**Comment by herjy** [comment]
I'm still suspicious though.

**Comment by pmelchior** [comment]
This seems to suggest that undersampling of the model is responsible. If so, we need to increase the width of the model PSF to ensure proper sampling, or (probably better) ensure that no gradient update forces the model to exceed the band-limit set by the model PSF.

**Comment by pmelchior** [comment]
closed in favor #222
