### ISSUE TITLE
autograd.np has no float

### ISSUE THREAD

**Issue by herjy** [pmelchior/scarlet#229]
https://github.com/pmelchior/scarlet/blob/1a9d339b058ba40755ec5a49b206cfe6c03bf958/scarlet/psf.py#L44

In this line `np` references `autograd.numpy`, which throws an error because it doesn't have a float attribute. 
Same happened in Wavelet L203, where `autograd.numpy.int` is called. 
Instead, we should `import numpy` and replace `np.float` by `numpy.float`.

**Comment by pmelchior** [comment]
Does `"float"` or `"int"` work instead?

**Comment by herjy** [comment]
It does. It's a much better solution indeed.

**Comment by pmelchior** [comment]
https://github.com/pmelchior/scarlet/blob/master/scarlet/wavelet.py#L202

is different because improper. Is this supposed to be a `floor`, `ceil`, `round` conversion?

**Comment by pmelchior** [comment]
From context, it doesn't seem to matter, so I'll use `round`.

**Comment by herjy** [comment]
I realize now that this problem might only come from me. It comes up in another place when running the multi-resolution NB,  which apparently does not happen when running the tests.

**Comment by pmelchior** [comment]
There's no such thing as a personalized code problem. The code is buggy at that line, and it's fixed in the active PR

**Comment by herjy** [comment]
Yes but there is such thing as version issues on a specific distribution, especially after updating a crapy product! Though my dependencies are up to date. The `Multiresolution` notebook won't work on my machine and returns this, which is the same problem: 
```
~/Desktop/git_repos/scarlet/scarlet/observation.py in match(self, model_frame)
    622         )
    623 
--> 624         center_y = np.int(
    625             self._fft_shape[0] / 2.0 - (self._fft_shape[0] - model_frame.Ny) / 2.0
    626         ) + ((self._fft_shape[0] % 2) != 0) * ((model_frame.Ny % 2) == 0)

AttributeError: module 'autograd.numpy' has no attribute 'int'
```
