### ISSUE TITLE
expand_dims fix breaks .match(model_frame)

### ISSUE THREAD

**Issue by patrickaleo** [pmelchior/scarlet#239]
Hi. I am following the docs tutorial here from the scarlet codebase: https://pmelchior.github.io/scarlet/0-quickstart.html 

I noticed that in commit 216e7813be6b205cf8506b2e42646f6c4644c5e0 there was a change to fix a depreciation, where `axis` in `np.expand_dims(model, axis=tuple(range(self._d)))` is now a `tuple`, which I believe may throw a TypeError when running `.match`. Here is the cell block I am running: 
```
model_frame = scarlet.Frame(
    images.shape,
    psf=model_psf,
    channels=filters)

observation = scarlet.Observation(
    images, 
    psf=psf,
    weights=weights, 
    channels=filters).match(model_frame)
```

and here is the full traceback:
<img width="959" alt="type_error" src="https://user-images.githubusercontent.com/12074873/110172568-f0ae1500-7dc2-11eb-9da9-4d1c362eddd1.png">

(I have run all cells perfectly before that, exactly matching the quick start tutorial.) Any advice would be greatly appreciated. Thanks!

**Comment by patrickaleo** [comment]
update: I still haven't figured out a solution modifying `axis`, so your thoughts are greatly appreciated!

**Comment by pmelchior** [comment]
I can't reproduce this problem. I run the code on python 3.7 without failure. I also tested autograd's numpy implementation for a range of dimensions. Can you check what your `PSF` instance reports as the `._d` attribute. This should be an integer, normally 1.

**Comment by patrickaleo** [comment]
I appreciate your help. I checked and my `model_psf._d` = 1. Though I also noticed that the line in the second cell of the tutorial `psf = scarlet.ImagePSF(data["psfs"])`, that this psf instance has many attributes but no `_d` attribute. It has ['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__next__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_children',
 '_parameters',
 'bbox',
 'check_parameters',
 'children',
 'get_model',
 'get_models_of_children',
 'get_parameter',
 'parameters',
 'prepare_param',
 'update']
 
 Not sure if that's helpful.

**Comment by fred3m** [comment]
Hi Patrick. We have tested this on multiple machines (mc OS, centos 7, centos 8), including in the LSST tests that run multiple times daily. The docs themselves are built with each PR on a fresh environment and are still building and running correctly.

So the most likely source of this is something in your python environment, most likely due to an old version of numpy. Could you please check (and potentially upgrade) your numpy version. If that doesn't work can you create a new clean environment and a fresh install of scarlet? We don't currently check the numpy version in the scarlet install but if this does fix your issue please let us know so that we can implement a minimum version.

**Comment by patrickaleo** [comment]
I really appreciate the help, and upgrading numpy worked (sorry I didn't think of this earlier)! Now the tutorial runs perfectly. Originally I had `numpy=1.17.4` (a clone of the default conda environment for our computing cluster), and now I have upgraded to`numpy=1.20.1` which works beautifully. So yes, I think it is wise to include a minimum version of numpy now in your scarlet install. Cheers!

**Comment by fred3m** [comment]
Great, thanks for the feedback. @pmelchior can you update this as part of #234 ? I _think_ that a minimum numpy version of `1.18.0` should work, but it might require `1.19.0`.
