### ISSUE TITLE
ModuleNotFoundError: No module named 'scarlet.operators_pybind11'

### ISSUE THREAD

**Issue by tcollett** [pmelchior/scarlet#251]
I ran through the install with no errors or warnings, but when I import scarlet I get this:

  File "/users/tec/scarlet/scarlet/__init__.py", line 2, in <module>
    from .blend import Blend
  File "/users/tec/scarlet/scarlet/blend.py", line 10, in <module>
    from .component import CombinedComponent
  File "/users/tec/scarlet/scarlet/component.py", line 9, in <module>
    from .morphology import Morphology
  File "/users/tec/scarlet/scarlet/morphology.py", line 20, in <module>
    from . import initialization
  File "/users/tec/scarlet/scarlet/initialization.py", line 6, in <module>
    from .renderer import NullRenderer, ConvolutionRenderer
  File "/users/tec/scarlet/scarlet/renderer.py", line 9, in <module>
    from scarlet.operators_pybind11 import apply_filter
ModuleNotFoundError: No module named 'scarlet.operators_pybind11'

I have operators_pybind11.cc in my scarlet folder, so I wonder if something in the install didn't wrap this correctly?

**Comment by herjy** [comment]
Hey Tom, sorry for not coming back earlier on this. What's your OS and python version?

**Comment by tcollett** [comment]
No problem. It's Python 3.7 and CentOS Linux 7

**Comment by herjy** [comment]
Are you running this in a conda environment? And are you trying to import scarlet from within the scarlet repo? (If yes, try importing it from somewhere else)

**Comment by pmelchior** [comment]
@tcollett Did that help? If so, please close the issue.

**Comment by tcollett** [comment]
Thanks @herjy, that seems to be importing now that I'm in a different directory. 

I'll start running through the tutorials. Fingers crossed.
