### ISSUE TITLE
setup.py doesn't work

### ISSUE THREAD

**Issue by silkerice** [pmelchior/scarlet#261]
I'm trying to install scarlet but I'm running into some issues. I installed all dependencies and I was following the steps mentioned in the installation guide. However when I try to run **python setup.py install** as was recommended in the installation guide, I get the following error:

Exception: Could not find either a git repo or pre-installed version.This should never happen, please open an issue at www.github.com/pmelchior/scarletso that it can be corrected.

I also tried installing it via **pip install .** or **pip install setup.py**, but I get the following error:

ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Can somebody help me with this issue?

**Comment by herjy** [comment]
This is the same as issue #237. 
Please try updating your version of git. 
Thanks for reporting this, we need to make the error message more explicit.

**Comment by silkerice** [comment]
Thank you for your quick response! Updating git solved my issue.
