### ISSUE TITLE
Quick Start Quide: No model

### ISSUE THREAD

**Issue by dhalvor** [pmelchior/scarlet#263]
When working through the quick start guide, I can't seem to render the model. I think this issue might have to do with the blend function from the earlier line, as my graph and runtime are pretty different to that in the guide. Images included. 
![Screenshot from 2022-02-04 12-56-43](https://user-images.githubusercontent.com/97866735/152460133-2d2892ff-0b3f-4730-97c6-4e86ed843255.png)
![Screenshot from 2022-02-04 12-56-17](https://user-images.githubusercontent.com/97866735/152460137-bec01bd4-8107-4342-ae46-9f7e98e7e5b5.png)

**Comment by pmelchior** [comment]
Hi dhalvor. Something is clearly wrong here. How did you initialize the models? Are asked differently, how would `blend.get_model()` look without running `blend.fit`?

**Comment by dhalvor** [comment]
Apologies for the late response, I'm assuming this is what you mean? I get the same result.
![image](https://user-images.githubusercontent.com/97866735/160334053-e7e66429-edfa-400a-a8db-1e2e1bf88697.png)
![image](https://user-images.githubusercontent.com/97866735/160334237-8d288a90-b935-46af-beff-f421424cecf7.png)
![image](https://user-images.githubusercontent.com/97866735/160334287-7ddeaee4-9bce-4b0e-a1ae-399ae989e38e.png)

**Comment by pmelchior** [comment]
How do you initialize these sources? Did you make any modifications to the quickstart procedure? The locations looks OK, so I'm guessing that the spectral are all zero-ish.

**Comment by dhalvor** [comment]
This seems to be the problem. I must have edited it at some point and removed the comma when defining the value of sigma for model_psf
![image](https://user-images.githubusercontent.com/97866735/160600936-4cbb498c-93eb-456c-a6aa-261954f1e9ed.png)
When I keep the comma (as it is in the quick start guide) it works just fine. However I'm not sure why missing a comma in this case would cause this problem, as all other examples of the GaussianPSF function take an normal float input just fin, however here when multiplying by the length of filters, the comma is needed?
